# Generated by Django 2.0.6 on 2019-01-04 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(blank=True, max_length=45, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=45, null=True)),
                ('nomecompleto', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(default='', max_length=75, unique=True, verbose_name='email')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('registration_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('valor_bike', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='A partir')),
                ('is_atendido', models.BooleanField(default=False, verbose_name='Até')),
            ],
            options={
                'verbose_name': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('preco_seguro', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Preço do Seguro')),
            ],
            options={
                'verbose_name': 'Proposta',
            },
        ),
        migrations.CreateModel(
            name='Seguradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=254, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Seguradora',
            },
        ),
        migrations.CreateModel(
            name='SeguradoraParametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('a_partir', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='A partir')),
                ('ate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Até')),
                ('is_apartir', models.BooleanField(verbose_name='A partir')),
                ('is_ate', models.BooleanField(verbose_name='Até')),
            ],
            options={
                'verbose_name': 'Seguradora Paramentro',
            },
        ),
        migrations.AddField(
            model_name='proposta',
            name='seguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='default.Seguradora', verbose_name='Seguradora'),
        ),
    ]
