# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2019-01-03 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('valor_bike', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='A partir')),
                ('is_atendido', models.BooleanField(default=False, verbose_name='Até')),
            ],
            options={
                'verbose_name': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('preco_seguro', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Preço do Seguro')),
            ],
            options={
                'verbose_name': 'Pedido',
            },
        ),
        migrations.CreateModel(
            name='Seguradora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=254, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Seguradora',
            },
        ),
        migrations.CreateModel(
            name='SeguradoraParametro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_removed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('a_partir', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='A partir')),
                ('ate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Até')),
                ('is_apartir', models.BooleanField(verbose_name='A partir')),
                ('is_ate', models.BooleanField(verbose_name='Até')),
            ],
            options={
                'verbose_name': 'Seguradora Paramentro',
            },
        ),
        migrations.AddField(
            model_name='proposta',
            name='seguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='default.Seguradora', verbose_name='Seguradora'),
        ),
    ]
