# Generated by Django 2.0.8 on 2019-01-07 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_proposta_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguradoraparametro',
            name='seguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='default.Seguradora', verbose_name='Seguradora'),
        ),
        migrations.AddField(
            model_name='seguradoraparametro',
            name='taxa_seguro',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Taxa do Seguro'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='is_atendido',
            field=models.BooleanField(default=False, verbose_name='É atendido ?'),
        ),
        migrations.AlterField(
            model_name='seguradoraparametro',
            name='a_partir',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='A partir'),
        ),
        migrations.AlterField(
            model_name='seguradoraparametro',
            name='ate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Até'),
        ),
    ]
