# Generated by Django 2.0.8 on 2019-01-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0005_auto_20190107_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguradoraparametro',
            name='a_partir',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=14, null=True, verbose_name='A partir'),
        ),
        migrations.AlterField(
            model_name='seguradoraparametro',
            name='ate',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=14, null=True, verbose_name='Até'),
        ),
    ]
