# Generated by Django 2.0.8 on 2019-01-07 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0006_auto_20190107_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='default.Pedido'),
        ),
    ]
